[project]
name    = "veryl_sample"
version = "0.3.0"
license = "MIT"

[build]
clock_type    = "posedge"
reset_type    = "async_low"
filelist_type = "absolute"
target        = {type = "source"}

[format]
indent_width = 4

[publish]
bump_commit    = true
publish_commit = true

[dependencies]
